_BASE_: ade20k-150/maskformer_R50_bs16_160k.yaml
DATASETS:
  TRAIN: ("EndoCV_train",)
  TEST: ("EndoCV_test",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0001 #0.000035 #0.0000125
  CHECKPOINT_PERIOD: 1000
  MAX_ITER: 200000
INPUT:
#  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 512) for x in range(5, 21)]"]
#  MIN_SIZE_TRAIN_SAMPLING: "choice"
#  MIN_SIZE_TEST: 512
#  MAX_SIZE_TRAIN: 2048
#  MAX_SIZE_TEST: 2048
#  CROP:
#    ENABLED: True
#    TYPE: "absolute"
#    SIZE: (512, 512)
#    SINGLE_CATEGORY_MAX_AREA: 1.0
#  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 0
#  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic_sequence"

TEST:
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: False
    MIN_SIZES: [256, 384, 512, 640, 768, 896]
    MAX_SIZE: 3584
    FLIP: True
MODEL:
  PIXEL_MEAN: [ 47.1753,  68.1616, 114.5232]
  PIXEL_STD: [43.5314, 53.7683, 79.8180]
  MASK_FORMER:
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    DIM_FEEDFORWARD: 1024
    NUM_OBJECT_QUERIES: 50
    DEEP_SUPERVISION: False
  SEM_SEG_HEAD:
    NUM_CLASSES: 1
    IGNORE_VALUE: 0
    MASK_DIM: 64
  SWIN:
    EMBED_DIM: 48
#    DEPTHS: [2, 2, 6, 2]
#    NUM_HEADS: [3, 6, 12, 24]
#    WINDOW_SIZE: 7
#    APE: False
#    DROP_PATH_RATE: 0.3
#    PATCH_NORM: True
OUTPUT_DIR: /datasets/MaskFormerOutput/output_EndoCV_preprocessed_images_non_empty_masks_weight_ce_loss_sigmoid_focal_loss_gamma_1
SEED: 1
